spring:
  application:
    name: payment
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/paymentservice
    username: postgres
    password: root


logging:
  level:
    org:
      springframework:
        security=DEBUG: